In [1]:
import pandas as pd
import numpy as np

In [2]:
#Sample info based on Table S2 https://www.biorxiv.org/content/biorxiv/early/2022/05/24/2022.05.24.493188/DC3/embed/media-3.xlsx?download=true
sample_table = pd.read_table("samples.txt", header=None)
sample_table.columns=["colname", "si"]
sample_table["Rep"] = sample_table["colname"].str.split("_").str[-1]
sample_table["id"] = sample_table["colname"].str.split("_").str[-2]
sample_table["Sample"] = sample_table["si"] + "_" + sample_table["colname"]
sample_table.to_csv("sample_all.txt", sep="\t", index=False)
sample_table.head()

               colname       si   Rep       id                       Sample
0         Ctrl_d3_rep1  Control  rep1       d3         Control_Ctrl_d3_rep1
1         Ctrl_d3_rep2  Control  rep2       d3         Control_Ctrl_d3_rep2
2  21_011_Control_rep1  Control  rep1  Control  Control_21_011_Control_rep1
3  21_011_Control_rep2  Control  rep2  Control  Control_21_011_Control_rep2
4         Control_rep1  Control  rep1  Control         Control_Control_rep1

In [3]:
#Clusters from Table S4 https://www.biorxiv.org/content/biorxiv/early/2022/05/24/2022.05.24.493188/DC5/embed/media-5.xlsx?download=true
clusters = pd.read_excel("media-5.xlsx")
clusters = clusters.rename(columns={"Unnamed: 0": "Gene", "NIPBL7": "NIPBL", 
                                    "Rad21": "RAD21", "Rad21_NIPBL": "RAD21.NIPBL", 
                                    "Mau2": "MAU2"})
clusters.head()

,Gene,RAD21,NIPBL,RAD21.NIPBL,MAU2,WAPL,PDS5A,PDS5B,PDS5AB,ESCO1,CTCF,JQ1,Cluster
0,YTHDF3,1,0,0,0,0,0,0,0,0,0,0,0
1,MYOZ2,1,0,0,0,0,0,0,0,0,0,0,0
2,RASGRP3,1,0,0,0,0,0,0,0,0,0,0,0
3,ELF1,1,0,0,0,0,0,0,0,0,0,0,0
4,RBP1,0,0,0,0,1,0,0,0,0,0,0,0

In [4]:
#Counts from GEO https://ftp.ncbi.nlm.nih.gov/geo/series/GSE196nnn/GSE196449/suppl/GSE196449%5FAllsamples.GRCh38.xlsx
counts = pd.read_excel("GSE196449_Allsamples.GRCh38.xlsx")
counts = counts.rename(columns={"Unnamed: 0": "Gene", "Unnamed: 1": "ensembl_id"})
counts = counts.rename(columns=dict(zip(sample_table.colname,sample_table.Sample)))
counts.head()

,Gene,ensembl_id,Control_Ctrl_d3_rep1,Control_Ctrl_d3_rep2,Control_21_011_Control_rep1,Control_21_011_Control_rep2,Control_Control_rep1,Control_Control_rep2,Rad21_si621_d2_rep1,Rad21_si621_d2_rep2,...,Pds5ab_si88_si91_rep1,Pds5ab_si88_si91_rep2,JQ1_21_011_JQ1_rep1,JQ1_21_011_JQ1_rep2,chromosome,strand,start,end,length,type
0,TSPAN6,ENSG00000000003,798.0,922.00,519.0,484.0,660.0,698.0,699.0,855.0,...,816.0,803.00,502.0,502.0,chrX,-,100627108,100637104,9996,protein_coding
1,TNMD,ENSG00000000005,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.00,0.0,0.0,chrX,+,100584935,100599885,14950,protein_coding
2,DPM1,ENSG00000000419,698.0,855.00,678.0,642.0,822.0,920.0,570.0,611.0,...,684.0,592.00,634.0,576.0,chr20,-,50934866,50958555,23689,protein_coding
3,SCYL3,ENSG00000000457,341.0,392.00,258.0,266.0,305.0,379.0,392.0,433.0,...,522.0,482.91,266.0,318.0,chr1,-,169849630,169893896,44266,protein_coding
4,C1orf112,ENSG00000000460,500.0,523.99,131.0,132.0,303.0,504.0,291.0,340.0,...,128.0,104.00,61.0,71.0,chr1,+,169795039,169854080,59041,protein_coding

In [5]:
counts = pd.merge(counts, clusters, on="Gene", how="left")
counts["Cluster"] = np.where(np.isnan(counts["Cluster"]), "None", counts["Cluster"])
counts.head()

,Gene,ensembl_id,Control_Ctrl_d3_rep1,Control_Ctrl_d3_rep2,Control_21_011_Control_rep1,Control_21_011_Control_rep2,Control_Control_rep1,Control_Control_rep2,Rad21_si621_d2_rep1,Rad21_si621_d2_rep2,...,RAD21.NIPBL,MAU2,WAPL,PDS5A,PDS5B,PDS5AB,ESCO1,CTCF,JQ1,Cluster
0,TSPAN6,ENSG00000000003,798.0,922.00,519.0,484.0,660.0,698.0,699.0,855.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
1,TNMD,ENSG00000000005,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
2,DPM1,ENSG00000000419,698.0,855.00,678.0,642.0,822.0,920.0,570.0,611.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
3,SCYL3,ENSG00000000457,341.0,392.00,258.0,266.0,305.0,379.0,392.0,433.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None
4,C1orf112,ENSG00000000460,500.0,523.99,131.0,132.0,303.0,504.0,291.0,340.0,...,0.0,0.0,-1.0,-1.0,0.0,0.0,0.0,0.0,0.0,3.0

In [6]:
counts.to_csv("GSE196449_Allsamples.GRCh38_counts_processed_all.txt", sep="\t", index=False)

In [7]:
### Download E2G predictions and merge
#wget https://www.encodeproject.org/files/ENCFF182EGZ/@@download/ENCFF182EGZ.bed.gz
#wget https://www.encodeproject.org/files/ENCFF958JJL/@@download/ENCFF958JJL.bed.gz
#wget https://www.encodeproject.org/files/ENCFF543WEF/@@download/ENCFF543WEF.bed.gz
#wget https://www.encodeproject.org/files/ENCFF228EZM/@@download/ENCFF228EZM.bed.gz
#gunzip ENCFF*gz
#cat ENCFF*bed | bedtools sort -i > merge_rE2G_retina.bed

In [8]:
### Download CTCF peaks
#wget https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5899nnn/GSM5899605/suppl/GSM5899605%5Fspikein.100.2017%5F034B%5FCt%5FCTCF.peak.bed.gz
#wget https://ftp.ncbi.nlm.nih.gov/geo/samples/GSM5899nnn/GSM5899621/suppl/GSM5899621%5Fspikein.100.2018%5F014A%5F015B%5FCt%5FCTCF.peak.bed.gz
#gunzip GSM5899*gz
#cat GSM5899*bed | bedtools sort -i | bedtools merge > CTCF_RPE1_merged.bed